// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oocknurhznuzmdpnkcpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vY2tudXJoem51em1kcG5rY3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDc0ODQsImV4cCI6MjA2ODMyMzQ4NH0.rmRTke3g6KDm8-EMF6722vqe9mCz9f8LRBMXSto8ANM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});